name: STVV Auto Post

on:
  workflow_dispatch:
  schedule:
    # JST 08:00
    - cron: "0 23 * * *"
    # JST 10:30
    - cron: "30 1 * * *"
    # JST 12:30
    - cron: "30 3 * * *"
    # JST 15:30
    - cron: "30 6 * * *"
    # JST 18:00
    - cron: "0 9 * * *"
    # JST 21:00
    - cron: "0 12 * * *"
    # JST 23:00
    - cron: "0 14 * * *"

permissions:
  contents: write

jobs:
  post:
   runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.12"

      - name: Install packages
        run: pip install requests beautifulsoup4 pillow

      - name: Generate STVV LAB image
        env:
          API_FOOTBALL_KEY: ${{ secrets.API_FOOTBALL_KEY }}
        run: python generate_image.py

      - name: Save generated image to GitHub
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"

          git add generated/match_lab.png

          if git diff --cached --quiet; then
            echo "No image changes"
          else
            git commit -m "Update STVV LAB image"
            git push
          fi

      - name: Run STVV auto post
        env:
          BUFFER_API_KEY: ${{ secrets.BUFFER_API_KEY }}
          API_FOOTBALL_KEY: ${{ secrets.API_FOOTBALL_KEY }}
        run: python stvv_post.py
